Resources:
  mycodecommit:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryDescription: "soma"
      RepositoryName: "AWScodecommit"

  myuser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: Soma@6393
      Policies:
        - PolicyName: loki
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codecommit:*
                Resource: "*"